.github/workflows/blossom-ci.yml
- Added YAML for CI integration to github repo
=> Initializing CI Actions

.github/workflows/blossom-ci.yml
- Testing CI system triggers
- Updating YAML if needed
=> CI YAML Updating

README.md
Updating readme for release with install notes
=> Readme update for v0.1.0

CONTRIBUTING.md, README.md
Updated the readme and contribution guidelines
=> Updates to contribution guidelines

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Just a minor update to the title format of the Github templates
=> Adjustments to Github Templates

modulus/datapipes/gnn/__init__.py, modulus/datapipes/gnn/vortex_shedding_dataset.py, test/datapipes/test_ahmed_body.py
Fixing a small bug in the vortex shedding dataloader
=> Bug ext vortex shedding datapipe

modulus/datapipes/climate/sfno/dataloaders/dali_es_helper_2d.py, modulus/datapipes/climate/sfno/dataloaders/data_loader_dali_2d.py, modulus/models/sfno/factorizations.py
Fix for length when adding solar zenith angle
=> Fix sizes when adding solar zenith angle

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/__init__.py
=> Version update 0.2.0

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Closes: https://github.com/NVIDIA/modulus/issues/99
Updating some of the issue template labels to be better
=> Adding better auto labels for issue templates

CHANGELOG.md, modulus/__init__.py
Closes: https://github.com/NVIDIA/modulus/issues/100
Updating main branch to a higher pre-release version. This will make sure install from source always has priority over 
=> Updating main to 0.3.0a0

CHANGELOG.md, pyproject.toml
=> Hot-fix security issues with certifi

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, docs/api/modulus.datapipes.rst, docs/api/modulus.models.rst, docs/api/modulus.utils.rst, modulus/utils/capture.py, pyproject.toml
Rebasing RC branch onto main. Will delete RC banch when complete:
Closes: https://github.com/NVIDIA/modulus/issues/125
=> 0.2.0 rc rebase into main

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
closes https://github.com/NVIDIA/modulus/issues/114
=> update contribution doc and PR template

modulus/models/meshgraphnet/meshgraphnet.py
closes https://github.com/NVIDIA/modulus/issues/86
=> flexible processor layer size for meshgraphnet

CHANGELOG.md, Dockerfile
Updates the base pytorch container. Also adds cleanup for `dgl` and fixes the version of `tensorflow` for faster install.
=> Update base container

CHANGELOG.md, Dockerfile
Fixes Modulus CI image with ghost modulus install, see related issue for details.
Closes: https://github.com/NVIDIA/modulus/issues/148
=> Fixing CI image

Dockerfile, README.md, pyproject.toml, test/conftest.py, test/datapipes/test_ahmed_body.py, test/datapipes/test_climate_hdf5.py, test/datapipes/test_darcy.py, test/datapipes/test_era5_hdf5.py, test/datapipes/test_kelvin_helmholtz.py, test/models/graphcast/test_concat_trick.py, test/models/graphcast/test_cugraphops.py, test/models/graphcast/test_grad_checkpointing.py, test/models/graphcast/test_graphcast.py, test/models/graphcast/utils.py, test/models/meshgraphnet/test_meshgraphnet.py, test/models/sfno/test_sfno.py, test/models/test_entrypoints.py, test/models/test_fcn_mip_plugin.py, test/pytest_utils.py, test/utils/graphcast/test_coordinate_transform.py, test/utils/sfno/test_yparams.py, test/utils/test_capture.py
This PR improves how we handle Modulus dependencies and also improves error handling for pytests in events of missing packages. 
Closes #141
=> Dependency cleanup and improve error handling for PyTests

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, modulus/__init__.py
House keeping with the versions for this release.
Close: https://github.com/NVIDIA/modulus/issues/162
=> 0.3.0 version update

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Dockerfile, README.md, modulus/__init__.py, modulus/models/module.py, pyproject.toml, test/conftest.py, test/datapipes/test_ahmed_body.py, test/datapipes/test_climate_hdf5.py, test/datapipes/test_darcy.py, test/datapipes/test_era5_hdf5.py, test/datapipes/test_kelvin_helmholtz.py, test/models/graphcast/test_concat_trick.py, test/models/graphcast/test_cugraphops.py, test/models/graphcast/test_grad_checkpointing.py, test/models/graphcast/test_graphcast.py, test/models/graphcast/utils.py, test/models/meshgraphnet/test_meshgraphnet.py, test/models/sfno/test_sfno.py, test/models/test_entrypoints.py, test/models/test_fcn_mip_plugin.py, test/pytest_utils.py, test/utils/graphcast/test_coordinate_transform.py, test/utils/sfno/test_yparams.py, test/utils/test_capture.py
=> 0.3.0 rc rebase

modulus/datapipes/gnn/ahmed_body_dataset.py
closes https://github.com/NVIDIA/modulus/issues/143
=> update the normalization in Ahmed body datapipe

.pre-commit-config.yaml, pyproject.toml, test/coverage.docstring.rc
=> exclude experimental from ci

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, modulus/__init__.py
=> Version update 0.4.0

docs/api/modulus.models.rst
=> Hot fix docs

docs/api/modulus.launch.logging.rst, docs/api/modulus.launch.utils.rst, docs/index.rst
Small PR to add Launch API docs
- [] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
=> update api docs to add launch content too

modulus/experimental/resdiff/generate.py
=> ResDiff integration: switch to pip install of edm sampler

Dockerfile
This PR attempts to fix the issues with mpi4py build during the docker build. It also fixes version for pip and setuptools and also adds `--no-cache-dir` flag to all the pip commands.
=> Update dockerfile to fix issues with mpi4py install

examples/generative/corrdiff/conf/config_generate.yaml, examples/generative/corrdiff/generate.py, examples/generative/corrdiff/module.py, modulus/models/diffusion/preconditioning.py, modulus/models/diffusion/unet.py
=> switch to modulus checkpointing for inference

CHANGELOG.md, pyproject.toml
Moving TQDM to a required dependency since its used in multiple spots... light weight package so I dont see too much of a problem.
Closes: https://github.com/NVIDIA/modulus/issues/280
=> Making TQDM a required dependency

examples/generative/corrdiff/conf/config_generate.yaml, examples/generative/corrdiff/conf/config_train.yaml, examples/generative/corrdiff/train.py, examples/generative/corrdiff/training/training_loop.py
=> fix training bugs

.github/workflows/blossom-ci.yml
=> Updating CI user list

examples/generative/corrdiff/conf/config_train.yaml, examples/generative/corrdiff/train.py, examples/generative/corrdiff/training/training_loop.py, modulus/metrics/diffusion/loss.py
=> ResDiff integratin: Enable modulus checkpointing for training

.github/workflows/blossom-ci.yml
Added @Alexey-Kamenev to the CI users list
=> Update CI users list

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, modulus/__init__.py
=> 0.5.0 Version Update

examples/generative/diffusion/dataset/dataset.py, examples/generative/diffusion/fid.py, examples/generative/diffusion/generate.py, examples/generative/diffusion/train.py, examples/generative/diffusion/training_loop.py, examples/generative/diffusion/training_stats.py
Updated diffusion example imports.
=> Fix diffusion example imports.

examples/weather/dlwp/train_dlwp.py, examples/weather/graphcast/constants.py
Updates the zenith angle import in the DLWP example. Adds type annotations to the GraphCast example configs (Similar to https://github.com/NVIDIA/modulus/pull/302).
=> Fix bugs in examples from weather directory

CHANGELOG.md, CITATION.cff
=> adding citation

CHANGELOG.md, examples/generative/corrdiff/README.md
Adding the link to the published CWA dataset for CorrDiff.
=> CorrDiff integration: Adding link to the CWA dataset

modulus/distributed/manager.py
Fix docstring indentation since it causes issues with [documentation](https://docs.nvidia.com/deeplearning/modulus/modulus-core/api/modulus.distributed.html#module-modulus.distributed.manager).
=> Fix docstring indentation.

CHANGELOG.md, Dockerfile, pyproject.toml
Updates the DGL build in the dockerfile and also updates the default base image. Closes #326 
Also moves `onnx` to the required dependency list as it is required by the inference pytests. 
Changes are tested by running pytests in both deploy and ci containers.
=> DGL install fixes, dependency updates 

CHANGELOG.md, modulus/distributed/manager.py, modulus/metrics/general/ensemble_metrics.py, test/distributed/test_manager.py, test/metrics/test_metrics_general.py
Closes https://github.com/NVIDIA/modulus/issues/277
No new dependencies
=> Consistently handle `world_size==1` in the `DistributedManager`

examples/weather/graphcast/constants.py, examples/weather/graphcast/train_graphcast.py
Fixing minor issues in GraphCast training
=> minor graphcast fixes

docs/index.rst, examples/README.md, examples/cfd/darcy_physics_informed/README.md, examples/molecular_dynamics/lennard_jones/README.md
- Adds hyperlink to each example entry in master readme
- Adds links to Sym's examples
- Few new additions (corrdiff) to the master readme and main docs, few fixes from rendering
=> README updates 02152024

examples/weather/fcn_afno/train_era5.py
=> Remove obsolete comment.

examples/minimal/neighbor_list/warp_neighbor_list.py, modulus/utils/__init__.py
=> Fix bug in importing Warp

examples/cfd/ahmed_body_mgn/conf/config.yaml, examples/cfd/ahmed_body_mgn/train.py, modulus/datapipes/gnn/ahmed_body_dataset.py
Improvements to Ahmed body dataset and example:
* improved initial dataset loading time.
* minor refactoring to the dataset
* added an option to control checkpoint frequency.
=> Improve initial data loading in Ahmed body example.

CHANGELOG.md, modulus/models/module.py
=> Enable strict=false when loading modulus checkpoints

CHANGELOG.md, modulus/models/diffusion/preconditioning.py
=> Revert "apply scaling to input but not conditioning data "

examples/generative/corrdiff/generate.py
=> switch to the updated Modulus module in CorrDiff inference

Dockerfile, modulus/__init__.py, test/deploy/test_onnx_fft.py, test/deploy/test_onnx_utils.py
Updated the PyTorch base container in preparation for the upcoming release. ONNX needs an update too due to the following bug that was fixed in this PR: https://github.com/microsoft/onnxruntime/pull/19419/files
=> Update library versions (PyTorch base container and ONNX)

examples/generative/corrdiff/README.md
=> CorrDiff: Add inference package link to readme

.github/workflows/blossom-ci.yml
=> Update blossom-ci authorized users

CHANGELOG.md, examples/generative/corrdiff/train.py, examples/generative/corrdiff/training/training_loop.py
Closes https://github.com/NVIDIA/modulus/issues/394
=> CorrDiff: wandb code logging

CHANGELOG.md, examples/generative/corrdiff/train.py, examples/generative/corrdiff/training/training_loop.py
Closes https://github.com/NVIDIA/modulus/issues/425, https://github.com/NVIDIA/modulus/issues/421
=> CorrDiff: Adding augmentation pipeline

CHANGELOG.md, modulus/utils/generative/sampler.py
Closes https://github.com/NVIDIA/modulus/issues/418
=> CorrDiff: Fix scaling bug in deterministic sampler

Dockerfile
=> Add dgl build from a custom built wheel for aarch64

examples/generative/corrdiff/training/training_loop.py
Closes https://github.com/NVIDIA/modulus/issues/441
=> save corrdiff checkpoints in verbose mode

CHANGELOG.md, modulus/utils/generative/__init__.py, modulus/utils/generative/utils.py
Closes https://github.com/NVIDIA/modulus/issues/437
=> CorrDiff: Remove pickle dependency

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, CITATION.cff, Dockerfile, README.md, modulus/__init__.py, modulus/utils/generative/__init__.py, modulus/utils/generative/utils.py, test/deploy/test_onnx_fft.py, test/deploy/test_onnx_utils.py
=> 0.6.0 rc rebase into main

modulus/datapipes/climate/climate.py
=> Update climate.py to patch scipy type hint

docs/Makefile, docs/api/modulus.distributed.rst, docs/index.rst, modulus/launch/logging/utils.py, modulus/models/graphcast/graph_cast_net.py
- adds commands for packaging the docs for CMS integration
- fix rendering issues in distributed docs
- update index.rst to be consistent with CMS
- indent fix in graphcast docstrings
- escape hyperlink in utils.py docs
=> Fix some doc related items

examples/generative/corrdiff/conf/config_train_base.yaml, examples/generative/corrdiff/training/training_loop.py
=> Fix CorrDiff config handling issue for gradient clipping

Dockerfile
With different base containers, we have different requirements for the wheels. This PR allows a mechanism to control this using a `build-arg`.
Also tested the build using just the defaults (in the absence of pre-built wheels)
Closes: https://github.com/NVIDIA/modulus/issues/453
=> 0.6.0 docker patch

test/models/test_nd_conv_layers.py
=> make updates to tests to avoid intermittent failures

CHANGELOG.md, Makefile, modulus/distributed/__init__.py, modulus/distributed/manager.py, test/distributed/test_manager.py
=> Raise a custom exception when querying undefined process groups

examples/generative/corrdiff/train.py, modulus/models/diffusion/__init__.py
=> CorrDiff: Preconditioning import bug fix

examples/generative/corrdiff/conf/config_train_base.yaml, examples/generative/corrdiff/train.py, examples/generative/corrdiff/training/training_loop.py
=> CorrDiff: Allreduced loss logging

Dockerfile, test/models/test_from_torch.py, test/models/test_model_factory.py, test/models/test_sfno.py
=> Fix SFNO tests in CI.

examples/cfd/vortex_shedding_mesh_reduced/train_sequence.py
=> Fixed model dumping in train_sequence

modulus/launch/utils/checkpoint.py
Fixes issue in checkpointing utility that causes an error when loading a checkpoint.
=> Fix error when loading a checkpoint.

CHANGELOG.md, examples/weather/graphcast/conf/config_small.yaml, examples/weather/graphcast/train_graphcast.py, examples/weather/graphcast/validation.py, modulus/datapipes/climate/era5_hdf5.py
Closes https://github.com/NVIDIA/modulus/issues/519
=> Support history > 0 in the ERA5 HDF5 datapipe

CHANGELOG.md, Makefile, modulus/distributed/__init__.py, modulus/distributed/manager.py, test/datapipes/test_healpix.py, test/distributed/test_manager.py, test/utils/test_capture.py, test/utils/test_checkpoint.py
closes #474 
Should be merged in after #469 
None
=> Safeguarding against usage of uninitialized DistributedManager

.github/workflows/blossom-ci.yml
Updates the workflow file based on latest guidance.
=> Make the User check exact

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/__init__.py
Release prep for 0.7.0 release
=> Update versions for 0.7.0 release

docs/tutorials/simple_training_example.rst
=> Fix typo in docs

CITATION.cff
This PR updates the citation text. Here's how the BibTeX is compiled in different formats:
Harvard:
Modulus Contributors. (2023). NVIDIA Modulus: An Open-source framework for building, training, and fine-tuning deep learning models for science and engineering. https://github.com/NVIDIA/modulus
IEEE:
Modulus Contributors, NVIDIA Modulus: An Open-source framework for building, training, and fine-tuning deep learning models for science and engineering. 2023. [Online]. Available: https://github.com/NVIDIA/modulus
APA:
Modulus Contributors. (2023). NVIDIA Modulus: An Open-source framework for building, training, and fine-tuning deep learning models for science and engineering. https://github.com/NVIDIA/modulus
MLA:
Modulus Contributors. NVIDIA Modulus: An Open-Source Framework for Building, …
=> [FEA] Update the citation text

Makefile
=> Exclude examples from pytest

examples/cfd/aero_graph_net/README.md, examples/healthcare/brain_anomaly_detection/README.md
Added `mailto:` to prevent 404 errors.
=> Fix email links

CHANGELOG.md, pyproject.toml
Some of our dependencies require Python 3.10+ and this is also the version inside our Docker containers.
=> Update required python version to 3.10

examples/generative/corrdiff/conf/config_generate.yaml, examples/generative/corrdiff/conf/config_generate_patch.yaml, examples/generative/corrdiff/conf/config_train_base.yaml, examples/generative/corrdiff/conf/references/config_data_ref.yaml, examples/generative/corrdiff/datasets/cwb.py, examples/generative/corrdiff/datasets/img_utils.py, examples/generative/corrdiff/tests/_regtest_outputs/test_dataset.test_Zarr_Dataset.out, examples/generative/corrdiff/tests/test_dataset.py
=> Revert "CorrDiff: CWB Dataloader cleanups"

examples/cfd/aero_graph_net/README.md
[utils.py](https://github.com/srib/modulus/blob/main/examples/cfd/aero_graph_net/utils.py) in `aero_graph_net` uses `shapely`. It is missing here. Adding `shapely` to installation. 
`shapely` for the example listed above.
=> Install shapely

examples/generative/corrdiff/generate.py, examples/generative/corrdiff/helpers/generate_helpers.py
=> corrdiff generate minor bugs fixed

.github/workflows/blossom-ci.yml
Step 1 towards enabling Multi-GPU CI.
=> Update blossom-ci.yml to include additional /multi-gpu-ci keyword

test/pytest_utils.py
Currently the version check uses pytest's importorskip to test for module version. However this only works if the `module.__version__` is a `str`. Notice the failures in the nightly builds ([reference](https://gitlab-master.nvidia.com/modulus/modulus-release-build-guide/-/jobs/107490389)):
```
======================================= short test summary info =======================================
FAILED test/models/graphcast/test_graphcast.py::test_graphcast_te_constructor - TypeError: expected string or bytes-like object
FAILED test/models/graphcast/test_graphcast.py::test_GraphCast_te_optims - TypeError: expected string or bytes-like object
FAILED test/models/graphcast/test_graphcast.py::test_graphcast_checkpoint_te - TypeError: expected string or bytes-like object …
```
=> Update the version checks for modules not returning module.__version_ as str

test/models/graphcast/test_graphcast_snmg.py, test/models/meshgraphnet/test_meshgraphnet_snmg.py
Update tolerances to fix multi-GPU failures
=> Fix multi-GPU test failures

examples/generative/corrdiff/generate.py, examples/generative/corrdiff/train.py
This fix multiple bugs in training and generation recipe, including loss scaling, config loading, and reversed image shapes
=> Fix bugs in training and generation recipe

CHANGELOG.md, examples/generative/corrdiff/conf/model/corrdiff_diffusion.yaml, examples/generative/corrdiff/conf/model/corrdiff_diffusion_mini.yaml, examples/generative/corrdiff/conf/model/corrdiff_patched_diffusion.yaml, examples/generative/corrdiff/train.py, modulus/models/diffusion/__init__.py, modulus/models/diffusion/preconditioning.py, test/models/diffusion/test_preconditioning.py, test/utils/corrdiff/test_generation_steps.py
=> CorrDiff: Refactore EDMPrecondSRV2 preconditioner and fix the metadata bug

examples/generative/corrdiff/README.md
=> Update link to CWA dataset

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/__init__.py
Update versions for 0.8.0 release preparation.
=> Update versions for 0.8.0 release

examples/cfd/aero_graph_net/conf/experiment/ahmed/mgn.yaml, examples/cfd/aero_graph_net/inference.py
Proper handling of the test set and values returned when `compute_drag` option is enabled.
=> Fix AGN example inference script.

examples/generative/corrdiff/README.md
Add link to CorrDiff-Mini dataset.
=> Update CorrDiff README.md

CHANGELOG.md, modulus/launch/logging/__init__.py
=> Fixed missing logging function export

examples/cfd/aero_graph_net/models.py, modulus/models/meshgraphnet/meshgraphnet.py
Adding `kwargs` to MGN/AGN `forward` method to enable support for models/dataloaders requiring additional parameters.
=> Add kwargs to MGN forward.

examples/generative/diffusion/README.md
The config path was incorrect in the Readme
=> Update the conf paths in docs

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/__init__.py
=> Update versions for 0.9.0

docs/index.rst
Remove the indices and tables as it adds very little value. Also, this makes the docs landing page consistent with the Sym's landing page.
=> Remove indices and tables from index.rst

examples/cfd/vortex_shedding_mgn/README.md
Adding warnings for tensorflow installation, as the latest tensorflow installation updates the numpy version inside the container causing a few other dependencies to fail. Flagged during internal QA [here](https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=4992284&cmtNo=).
=> Update README.md for vortex shedding example

.github/workflows/blossom-ci.yml
Allows me to run the CI pipeline via GH comments
=> Add pzharrington to blossom ci list

examples/cfd/external_aerodynamics/domino/src/conf/config.yaml, modulus/datapipes/cae/domino_datapipe.py, modulus/models/domino/model.py, modulus/utils/domino/utils.py
Making enhancements and fixes to the domino surface model
=> domino surface model enhancements and fixes

modulus/utils/domino/utils.py
=> Make vtk and pv dependencies optional for DoMINO

.github/workflows/blossom-ci.yml
=> add blossom user

.github/workflows/blossom-ci.yml
Adding Hamed Akhondzadeh to CI users.
=> Add CI user.

examples/healthcare/bloodflow_1d_mgn/README.md
=> add contributor to 1d bloodflow readme

.github/workflows/blossom-ci.yml, modulus/models/pix2pix/__init__.py, modulus/models/pix2pix/pix2pixunet.py
Added a unet pix2pix model to modulus.models
=> Add a Unet Version of Pix2Pix Model

examples/weather/flood_modeling/hydrographnet/README.md
Adding a placeholder for the HydroGraphNet model for river modeling
=> adding placeholder for hydrographnet

CHANGELOG.md, examples/cfd/external_aerodynamics/domino/src/openfoam_datapipe.py
Fixing bug introduced in the data processing script of the domino training example.
=> fixing bug in openfoam datapipe

CHANGELOG.md, physicsnemo/__init__.py
Include bug fixes to the pytorch versioning and entrypoint
=> Update for a patch release

CHANGELOG.md, physicsnemo/__init__.py
=> 1.0.1 rc rebase

physicsnemo/distributed/manager.py
Commenting out this setting, it impacts other packages as well.
=> Comment warning setting in DistributedManager

physicsnemo/models/domino/model.py
This PR makes one small change to DoMINO's model that substantially decreases the memory foot print during training.
=> Gather to index select

examples/generative/corrdiff/train.py
=> Catch improper use of path grad acc

CHANGELOG.md, physicsnemo/models/layers/ball_query.py, physicsnemo/utils/sdf.py
Need this explicit Warp device handling to get the multi-gpu functionality to work for the domino-automotive-aero NIM
=> Domino warp device allocation

examples/generative/stormcast/README.md, examples/generative/stormcast/config/inference/stormcast.yaml, examples/generative/stormcast/config/model/stormcast.yaml, examples/generative/stormcast/datasets/dataset.py, examples/generative/stormcast/inference.py, examples/generative/stormcast/utils/nn.py, examples/generative/stormcast/utils/trainer.py
This PR adds support for configurable model conditions to the StormCast recipe.
**Main changes**:
1. Add configuration parameters `model.regression_conditions` and `model.diffusion_conditions`. These are lists consisting of `'state'`, `'background'`, `'invariant'` and/or `'regression'` (`'regression'` can only be specified in `model.diffusion_conditions`). The defaults are set to correspond to the StormCast paper.
2. Eliminate redundant parameters and configuration options that are now handled by the new two options: `previous_step_conditioning`, `use_regression_net`.
3. Streamline code to utilize the new parameters, eliminating redundancies. Particularly `utils.nn. build_network_condition_and_target` and `utils.nn.regression_model_forward`, as well as the calculation of model input …
=> Stormcast customization conditions

examples/README.md
Fixes a broken link for the coupled DLWP-healpix model
=> Update DLWP-HPX link

examples/cfd/external_aerodynamics/domino/src/test.py, examples/generative/stormcast/utils/trainer.py, physicsnemo/utils/sdf.py
=> Exclusively fix linting errors.

physicsnemo/models/layers/ball_query.py, test/datapipes/test_domino_datapipe.py
=> Domino datapipe test

examples/generative/corrdiff/conf/base/training/base_all.yaml, examples/generative/corrdiff/train.py
update lr_decay_rate to be configurable
=> update lr_decay_rate to be configurable for CorrDiff

physicsnemo/models/domino/model.py
=> fixing model.py to make comapatible with NIM

CHANGELOG.md, physicsnemo/models/diffusion/song_unet.py
Add lead time embedding support for `positional_embedding_selector`
Enable arbitrary positioning of probabilistic variables
=> Update lead time embedding and probabilistic variables positioning in SongUNetPosEmb

examples/generative/corrdiff/train.py
Fix validation bug and adjust loss scaling for multi-iteration patching for CorrDiff
=> Fix validation bug and adjust loss scaling for multi-iteration patching for CorrDiff

examples/weather/corrdiff/datasets/cwb.py, examples/weather/corrdiff/datasets/dataset.py, examples/weather/corrdiff/datasets/gefs_hrrr.py, examples/weather/corrdiff/datasets/hrrrmini.py, examples/weather/corrdiff/generate.py, examples/weather/corrdiff/helpers/generate_helpers.py, examples/weather/corrdiff/helpers/train_helpers.py, examples/weather/corrdiff/inference/plot_multiple_samples.py, examples/weather/corrdiff/inference/plot_single_sample.py, examples/weather/corrdiff/inference/power_spectra.py, examples/weather/corrdiff/requirements.txt, examples/weather/corrdiff/score_samples.py, examples/weather/corrdiff/train.py
=> Added requirements.txt for corrdiff + fixed import paths

README.md
Update a handful of links to point to physicsnemo.
=> Update Main README Links

examples/cfd/stokes_mgn/raw_dataset/download_dataset.sh
Update the Stokes dataset to download from new location
=> Update the Stokes dataset to download from new location

docs/Makefile, docs/index.rst, examples/cfd/external_aerodynamics/aero_graph_net/README.md, examples/cfd/external_aerodynamics/xaeronet/README.md
Updates the path for certain images. Also make the image path handling in the docs generation more flexible.
=> Update to paths to images for certain docs

examples/cfd/external_aerodynamics/domino/README.md
Minor update to reflect the configs : https://github.com/NVIDIA/physicsnemo/blob/main/examples/cfd/external_aerodynamics/domino/src/conf/config.yaml#L149
=> Update README.md for DoMINO

examples/cfd/external_aerodynamics/domino/README.md, examples/cfd/external_aerodynamics/domino/src/test.py
Few minor updates to the `test.py` and testing sections in `README.md`
=> DoMINO `test.py` updates

physicsnemo/models/diffusion/layers.py
Closes https://github.com/NVIDIA/physicsnemo/issues/972
None
=> Fixing GroupNorm edge case with num_channels < min_channels_per_group or not perfectly divisible

physicsnemo/models/module.py
=> Fix type error in Module's overridable arguments

README.md
Updates the container version from 25.03 to 25.06, and adds a link to the curator repo.
=> Update README (container version, link to curator)

CHANGELOG.md, examples/cfd/darcy_transolver/requirements.txt, examples/cfd/darcy_transolver/train_transolver_darcy_fix.py, examples/cfd/external_aerodynamics/transolver/README.md, examples/cfd/external_aerodynamics/transolver/compute_normalizations.py, examples/cfd/external_aerodynamics/transolver/conf/train_surface.yaml, examples/cfd/external_aerodynamics/transolver/datapipe.py, examples/cfd/external_aerodynamics/transolver/inference_on_vtp.py, examples/cfd/external_aerodynamics/transolver/inference_on_zarr.py, examples/cfd/external_aerodynamics/transolver/loss.py, examples/cfd/external_aerodynamics/transolver/metrics.py, examples/cfd/external_aerodynamics/transolver/preprocess.py, examples/cfd/external_aerodynamics/transolver/requirements.txt, examples/cfd/external_aerodynamics/transolver/train.py
See https://github.com/NVIDIA/physicsnemo/pull/1022
This PR adds the example from that PR, there are no changes to core API.
=> Cfd transolver driverml example

CHANGELOG.md, examples/cfd/external_aerodynamics/domino/requirements.txt, physicsnemo/models/domino/model.py
=> Domino fixes

physicsnemo/distributed/shard_utils/__init__.py, physicsnemo/distributed/shard_utils/index_ops.py
Fix index select not using the correct precision in the backwards pass.
=> Fix import error from renaming index op items.

.gitlab-ci.yml
This PR will enable multigpu CI integration on gitlab.
=> Enable multi-gpu ci integration on internal clusters.

CHANGELOG.md, examples/molecular_dynamics/lennard_jones_dgl/README.md, examples/molecular_dynamics/lennard_jones_dgl/conf/config.yaml, examples/molecular_dynamics/lennard_jones_dgl/download_data.py, examples/molecular_dynamics/lennard_jones_dgl/lennard_jones_system.py, examples/molecular_dynamics/lennard_jones_dgl/requirements.txt, examples/molecular_dynamics/lennard_jones_dgl/utils.py
1. Added PyG-based Lennard Jones example.
2. Renamed existing DGL-based example to `lennard_jones_dgl`
| DGL | PyG |
|----------|----------|
|  <img width="500" height="500" alt="results_figure_35" src="https://github.com/user-attachments/assets/f2b558ee-2a33-4176-a3f3-bc8e858a11fd" />  |  <img width="500" height="500" alt="results_figure_35" src="https://github.com/user-attachments/assets/e551685d-4c17-4e8b-8370-06e67d61d132" />  |
=> Migrate Lennard Jones example to PyTorch Geometric

examples/cfd/external_aerodynamics/xaeronet/README.md
Fixes internal bug: https://nvbugspro.nvidia.com/bug/5020639
=> Update README.md for XAeroNet
