pyproject.toml

Fixing issue with git version locking for torch harmonics dependency
Original version was ignoring the git sha for torch-harmonics
```
Collecting torch-harmonics@ git+https://github.com/NVIDIA/torch-harmonics.git#egg=8826246cacf6c37b600cdd63fde210815ba238fd (from nvidia-modulus==0.1.0)
Cloning https://github.com/NVIDIA/torch-harmonics.git to /tmp/pip-install-840mn0gu/torch-harmonics_b52de40f1bbf416cbff12df2f60b44cb
Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/torch-harmonics.git /tmp/pip-install-840mn0gu/torch-harmonics_b52de40f1bbf416cbff12df2f60b44cb
Resolved https://github.com/NVIDIA/torch-harmonics.git to commit 786750f859e0e47d82a43bebe1e602539f59d373
```
Changes here fix that issue and respect the requested git sha:
```
Collecting torch-harmonics@ …
```

Torch harmonics dependency fix

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
modulus/__init__.py
modulus/utils/capture.py

Closes #107 
The workaround fix adds a time delay between the warmup steps and the start of the graph capture to allow enough time for NCCL watchdog to clean-up work. The fix was stress tested against AFNO example from Modulus Launch, and it passed 10/10 times. 

Hot-fix NCCL CUDA Graphs bug

---

CHANGELOG.md
modulus/models/fcn_mip_plugin.py
test/models/test_fcn_mip_plugin.py

This PR adds batching support for the DLWP wrapper needed for faster inference and also updates the time stepping such that the time passed to the wrapper is now corresponds to the latest timestep input to the model. 
Closes #137

Refactor DLWP wrapper and add batching support

---

CHANGELOG.md
modulus/models/module.py

Closes #127 
Specifying the members converts the severity to low as per [bandit docs](https://bandit.readthedocs.io/en/1.7.5/plugins/b202_tarfile_unsafe_members.html)
Checks the members before extracting such that the members:
* Don't try to traverse up the directory structure.
* Don't specify an absolute path to target arbitrary locations on the file system.
* Will be extracted within the intended target directory, even after resolving symbolic links and redundant path elements.

Use safer tar extract

---

Dockerfile

Fix installs in dockerfile, specifically, `pip install .[all]` will not work in Dockerfile because that will install warp-lang. We cannot include warp-lang in the release container due to license concerns.

Hot fix dockerfile deps

---

CHANGELOG.md
Dockerfile
README.md
modulus/models/gnn_layers/mesh_graph_mlp.py
modulus/models/layers/fused_silu.py
test/models/common/utils.py
test/models/graphcast/test_concat_trick.py
test/models/graphcast/test_cugraphops.py
test/models/test_layers_activations.py

A switch to the latest 23.10 PyTorch container will bring a change in NVFuser APIs. This PR tries to update the fused SiLu code to reflect that. It also moves the nvfuser imports so that it does not error out if not available. Addresses #60 
The pytests will now pass by skipping the tests that touch fused silu code (if nvfuser is not available). If someone tries to import the module explicitly, it will print the following error message (ref: https://github.com/NVIDIA/modulus/actions/runs/6568159141/job/17842143792):
```
Error: Either nvfuser is not installed or the version is incompatible. Please retry after installing correct version of nvfuser. The new version of nvfuser should be available in PyTorch container version >= 23.10. …
```

NVFuser fixes for 23.11 Modulus release

---

CHANGELOG.md
modulus/utils/filesystem.py
test/utils/test_filesystem.py

Adding NGC model file protocol for filesystem in Modulus. Allows users to fetch / unzip files on NGC model registry both public and private.
Users can now use `ngc://org/team/model/version/file` to fetch files from NGC. Also works with private registries if users have set `API_KEY` to the environment variable. If its a zip file, it will automatically unzip its contents. This can be very useful for shipping resources for examples and such.
Related to: https://github.com/NVIDIA/earth2mip/issues/57
Closes: https://github.com/NVIDIA/modulus/issues/217

Adding NGC model file support to filesystem

---

test/metrics/test_metrics_general.py

Fixes `test/metrics/test_metrics_general.py::test_crps` to use the histogram method for large ensemble sizes instead of the kernel method, which has longer runtimes.
Closes #224

fix crps to use kernel method for large ensemble sizes in pytest

---

Dockerfile
Makefile

Adds git hash to the docker container. If the build arg is not provided, it will default to unknown. 
Sample output:
```
docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 --runtime nvidia -v ${PWD}:/workspace -it modulus:deploy /bin/bash -c 'echo $MODULUS_GIT_HASH'
...
<header content>
...
9fc5d8b
```

Add git hash to the docker container

---

examples/cfd/ahmed_body_mgn/constants.py
examples/cfd/stokes_mgn/train.py

Pydantic v2 update requires changes to some apis. The Stokes flow example change is similar to the one done here: https://github.com/NVIDIA/modulus/pull/226. 
Pydantic also requires type annotations (ahmed body example fixes). 
```
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `hidden_dim_node_encoder = 256`. All model fields require a type annotation; if `hidden_dim_node_encoder` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
```

Fix pydantic issues

---

CHANGELOG.md
modulus/models/diffusion/preconditioning.py

This PR closes #229; where the scaling was originally applied to both the input `x` and the low resolution conditioning data `img_lr` and its now applied only to `x`.

apply scaling to input but not conditioning data 

---

CHANGELOG.md
examples/generative/corrdiff/train.py
modulus/models/diffusion/preconditioning.py
test/models/diffusion/test_preconditioning.py

This PR fixes the scaling for conditional inputs in corrdiff. Previously the conditional inputs were concatenated with the noisy target BEFORE scaling. This means that for large noise the conditional inputs will also be scaled down to near 0. This is undesirable since the large-noise limits corresponds to deterministic prediction---we expect the conditional inputs to matter most in this case! This PR fixes this by scaling the noise image BEFORE concatenating it with the conditioning.
I wrote this PR with unit testing in mind, so I wrote a modular class `_ConditionalPrecond` which is testable in isolation. I added a public API `EDMPrecondSRV2` to provide a similar interface as `EDMPrecondSR` that also builds the UNet.
Closes #229.

Fix corr-diff conditional scaling

---

pyproject.toml

Adding URLs to TOML meta data for python package parsers:
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls
Noticed this too many times with the pip license package failing to get a URL for modulus, decided to finally fix that hopefully.

Adding url meta data to TOML

---

examples/generative/corrdiff/train.py

When I ran the training example I got the following error at the end:
```
Traceback (most recent call last):
File "/code/modulus/examples/generative/corrdiff/train.py", line 335, in main
training_loop.training_loop(
TypeError: training_loop() missing 3 required positional arguments: 'dataset_iterator', 'validation_dataset', and 'validation_dataset_iterator'
```
The problem appears to be that `training_loop` is called twice in a nested fashion. Since the error is only thrown on the outside call after the first call completes, the error is only raised after the training has already completed (which is why this probably wasn't noticed earlier).

CorrDiff: Remove extra call to training_loop

---

test/metrics/test_loss_climate.py

CI failed intermittently on the `metrics/test_loss_climate.py`, while the exact cause is unknown, reducing the size of the tensor seems to help with the intermittency.

Address intermittent CI failures

---

CHANGELOG.md
modulus/metrics/general/crps.py
test/metrics/test_metrics_general.py

This PR adds another method for computing the Continuous Ranked Probability Score. It lifts the implementation from Earth2MIP, https://github.com/NVIDIA/earth2mip/blob/main/earth2mip/crps.py, at the request from @nbren12.
Closes #455

Add Sorted Empirical CDF CRPS algorithm

---

examples/generative/corrdiff/train.py

The existing patch based training check automatically assumes that the patch size is not the full region. If a full domain region that is rectangular is being trained It is incorrectly rejected as being patch based.
Updates the logic on the patch based size checking to avoid incorrectly rejecting full domain trainings.
Fixes issue: 
https://github.com/NVIDIA/modulus/issues/522

Update logic on corrdiff patch based training

---

CHANGELOG.md
examples/weather/graphcast/conf/config_small.yaml
examples/weather/graphcast/train_graphcast.py
examples/weather/graphcast/train_utils.py
examples/weather/graphcast/validation.py
modulus/datapipes/climate/era5_hdf5.py
modulus/datapipes/climate/utils/zenith_angle.py

Closes https://github.com/NVIDIA/modulus/issues/527

FEA: Support for cos zenith angle in the ERA5 HDF5 dataloader

---

modulus/datapipes/gnn/stokes_dataset.py
modulus/distributed/manager.py
modulus/launch/utils/checkpoint.py

This PR fixes a few following issues: 
1. Stokes dataset was not capturing all the edges of a graph. 
2. The error message printed by uninitialized distributed manager was incomplete. 
3. Distributed manager was uninitialized in the load checkpoint utility.

Misc fixes: Stokes dataset connectivity, distributed manager initialization and error messages

---

modulus/metrics/general/crps.py
test/metrics/test_metrics_general.py

Implements the unbiased (fair) versions of the CRPS formula.
This also harmonizes the CRPS implementations. Following Zamo and Naveau, the "kernel" and "sort" methods give identical answers. Also, there is a fast sort-based algorithm for the kernel formula (see the derivation in `_kernel_crps_implementation`). This is also used [by weather bench](https://github.com/google-research/weatherbench2/blob/main/weatherbench2/metrics.py#L715).
I could leave the existing `kcrps` and `_crps_from_empirical_crps` formulas, but seems worthwhile to harmonize the implementations.
Zamo, M., & Naveau, P. (2018). Estimation of the Continuous Ranked Probability Score with Limited Information and Applications to Ensemble Weather Forecasts. Mathematical Geosciences, 50(2), 209–234. …

CRPS improvements: fast and unbiased kernel implementations

---

examples/weather/diagnostic/diagnostic/loss.py

This PR fixes a bug where the latitude weights in the diagnostic model training example were computed incorrectly at the poles (and only at the poles).

Fix bug with latitude weighting

---

modulus/launch/logging/console.py

Hydra has several capabilities for logging management, including log capturing which are extremely useful for recording training logs.
The `PythonLogger` -- and by extension `LaunchLogger` -- does not work with this, as it resets any handlers set by hydra to set the loggin configuration. As a result, hydra's logging management has no effect the captured logs are empty for a majority of modulus examples that use both hydra & LaunchLogger extensively.
This PR removes the handler overrides, as currently they do not seem to be adding any other functionality.
None

Fix Hydra log management for PythonLogger

---

examples/generative/corrdiff/train.py

Fixing the issue with improper placement of the barrier that was causing processes to hang for multi-gpu runs

[Bug] Fix CorrDiff DDP issue

---

docs/test_scripts/test_mlflow_logger.py
examples/cfd/darcy_fno/train_fno_darcy.py
examples/cfd/darcy_nested_fnos/train_nested_darcy.py
examples/cfd/mhd_pino/train_mhd.py
examples/cfd/mhd_pino/train_mhd_vec_pot.py
examples/cfd/mhd_pino/train_mhd_vec_pot_tfno.py
examples/weather/diagnostic/train_diagnostic_precip.py
examples/weather/dlwp/train_dlwp.py
examples/weather/fcn_afno/train_era5.py
examples/weather/pangu_weather/train_pangu_era5.py
examples/weather/pangu_weather/train_pangu_lite_era5.py
examples/weather/unified_recipe/train.py
modulus/launch/logging/__init__.py

Fixes the mlflow import errors by removing `initialize_mlflow` from the init file. 
- [] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

Fix mlflow import errors

---

CHANGELOG.md
Dockerfile
modulus/__init__.py
modulus/utils/mesh/__init__.py
modulus/utils/mesh/generate_stl.py
modulus/utils/sdf.py
pyproject.toml
test/pytest_utils.py
test/utils/test_mesh_utils.py
test/utils/test_sdf.py

Adds a simple utility to generate STL from SDF. 
Also makes some changes to help with CI

[FEA]: SDF to STL utility using Marching Cubes

---

CHANGELOG.md
modulus/utils/capture.py
test/utils/test_capture.py

Adds `gradient_clip_norm` to the static capture utilities. This should be backward compatible with existing examples.

Add gradient clipping to Static Capture Utilities

---

CHANGELOG.md
modulus/datapipes/climate/climate.py
modulus/datapipes/climate/era5_hdf5.py
modulus/datapipes/climate/utils/zenith_angle.py

This PR fixes timezones in the ERA5 datapipes and in the related cosine zenith utilities. There was a discrepancy because of this that caused a `+3600` to appear to be correct, but was likely an artifact due to improperly set time zones.

Fix Timezone to UTC in Datapipes and Cosine Zenith

---

modulus/metrics/cae/cfd.py
test/metrics/test_metrics_cfd.py

Fixes shapely import errors in the deployment image which does not have shapely

Fix `shapely` import errors

---

modulus/launch/logging/wandb.py

Add W&B id parameter to the init function to enable resuming. Providing W&B id allows to have a single graph for multiple runs such as the following graph that contains data from 5 experiments with resuming:
Note that the actual id generation and storage is left up to the user since it can be different.

Add W&B id parameter to the init function to enable resuming.

---

test/datapipes/test_lagrangian.py

The `test_graph_construction` test was missing the decorator

Add `import_or_fail` decorator to lagranginan tests

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
modulus/__init__.py
modulus/datapipes/healpix/data_modules.py
modulus/datapipes/healpix/timeseries_dataset.py
test/datapipes/test_lagrangian.py
test/models/dlwp_healpix/test_healpix_layers.py

0.9.0 rc rebase 1

---

modulus/metrics/diffusion/loss.py

Previously `EDMLoss` passed the `labels` as a positional argument to the network call; this pattern was updated to use an explicit keyword arg when supporting conditional models, but the keyword `labels` used in unconditional case is not always defined/correct. This is a simple fix to revert unconditional `EDMLoss` usage to the previous behavior. I've tested this with the existing `examples/generative/diffusion` examples and a ReGenAI prototype, both succeeding.

Revert unconditional EDMLoss to positional arg

---

CHANGELOG.md
examples/cfd/external_aerodynamics/domino/README.md
examples/cfd/external_aerodynamics/domino/src/conf/config.yaml
examples/cfd/external_aerodynamics/domino/src/openfoam_datapipe.py
examples/cfd/external_aerodynamics/domino/src/retraining.py
examples/cfd/external_aerodynamics/domino/src/test.py
examples/cfd/external_aerodynamics/domino/src/train.py
modulus/datapipes/cae/domino_datapipe.py

I have added a minimal retraining recipe and validated it with Luminary Cloud dataset we had generated for SC'24.  Also, the non-dimensionalization of flow variables is moved out of domino_datapipe.py to openfoam_datapipe.py so that users can have more control over the order and type of solution variables they can model.

Retraining recipe for DoMINO and removing fixed non-dimensionalization from domino datapipe

---

Dockerfile
test/deploy/ort_utils.py
test/deploy/test_onnx_fft.py
test/deploy/test_onnx_utils.py

Changes to Dockerfile and tests to handle onnxruntime dependency. 
Onnx is still not shipping arm wheels, hence the installation from a pre-built wheel. Additionally, the tests can now be safely changed to support any onnxruntime version > 1.19.0 as the change is upstreamed.

Dockerfile changes to handle onnxruntime dependency

---

Dockerfile

Dockerfile Fixes

---

pyproject.toml

When installing PhysicsNeMo from source with `setuptools>=77` (current latest release is v78), the following deprecation warning is emitted during install, from PhysicsNeMo:
```
SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also
use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for
details.
**************************************************************************** …
```

Fixes DeprecationWarning introduced in setuptools>=77

---

physicsnemo/datapipes/cae/domino_datapipe.py
physicsnemo/utils/sdf.py

This commit addresses an issue where the mesh indexes were being improperly converted to float32 at some point.  This enables the preprocessing workflow to stay on the GPU for this section, if the data is on GPU.

Fix CUPY float/int datatype casting.

---

examples/cfd/external_aerodynamics/domino/src/train.py

This commit creates alternative versions of the domino loss functions that are significantly simpler and shorter, while producing numerically consistent results.
Original functions are maintained in this commit and the training script compares individual loss components as well as total loss.
This commit also ensure `area` has the right dimension in the train and validation loop.  It's unchanged in the data sources or anywhere else (the model unsqueezes it too).  That is still a general issue to resolve, but the loss should be correct here.

Domino Loss Functions

---

.github/workflows/blossom-ci.yml

Adding abokov-nv to authorized users to trigger blossom-ci.yml

Adding abokov-nv to authorized users to trigger blossom-ci.yml

---

examples/generative/corrdiff/README.md
examples/generative/corrdiff/datasets/__init__.py
examples/generative/corrdiff/datasets/dataset.py
examples/generative/corrdiff/generate.py
examples/generative/corrdiff/train.py
physicsnemo/metrics/diffusion/loss.py
physicsnemo/utils/patching.py

This PR addresses multiple bugs related to CorrDiff training and inference:
- It improves clarity regarding (cross-)validation through documentation and variable renaming.
- It removes duplicate code from `ResidualLoss`
- Automatically disables AMP for inference in `generate.py` (bug reported in #874).
- Implements no-ops fallbacks for profiling tools when torch is built without cuda support (useful to run hrrr-mini on CPU)
Closes #860.
None.

CorrDiff: inference bugfixes, cleanup, and documentation improvements

---

CONTRIBUTING.md
Makefile
test/conftest.py
test/datapipes/test_ahmed_body.py
test/datapipes/test_bsms.py
test/datapipes/test_climate.py
test/datapipes/test_drivaernet.py
test/datapipes/test_healpix.py
test/datapipes/test_healpix_couple.py
test/datapipes/test_lagrangian.py
test/datapipes/test_mesh_datapipe.py
test/datapipes/test_stokes.py
test/metrics/test_healpix_loss.py
test/models/meshgraphnet/test_bsms_mgn.py
test/models/test_fcn_mip_plugin.py
test/models/test_unet.py
test/pytest_utils.py

Some of the unit tests require test data, currently it's hardcoded to `/data/nfs/modulus-data` and defined in a few places independently. `@nfsdata_or_fail` decorator is used to check if the expected path is present on the system and marks test as skipped if it needs data, but it is not there.
The problem with that approach is that you need root permissions to be able to create this `/data` folder on the system.
We should be more flexible and allow user to override that default path if needed.

Making the unit tests' nfs-data-dir configurable

---

test/utils/test_checkpoint.py
test/utils/test_msc_public_read.py

Updating some tests to use the `import_or_fail` decorator.

Update msc test with import_or_skip decorator

---

examples/cfd/external_aerodynamics/domino/src/conf/config.yaml
physicsnemo/datapipes/cae/domino_datapipe.py
physicsnemo/datapipes/cae/domino_sharded_datapipe.py

This PR fixes a bug: it's difficult to configure the data processing path in domino.
Now, the yaml config can be used to direct the device used for preprocessing.

Bug fix configure domino pipeline device

---

physicsnemo/utils/patching.py

After unfold we need to undo the `view(dtype)` with another `view(...)` instead of a `.to`. For instance,
```
t = torch.arange(10)
t.view(torch.float64).to(t.dtype)
```
gives only zeros and this affected the computation of `global_index`.

Fix dtype casting after unfold

---

CHANGELOG.md
Dockerfile
pyproject.toml

Make the dali package optional. 
This allows the following steps to run from the base install:
```
conda create --name custom-env python=3.12
conda activate custom-env
pip install .
pip install -r requirements.txt
python train_fno_darcy.py
```

Make NVIDIA Dali optional

---

physicsnemo/__init__.py
physicsnemo/utils/generative/deterministic_sampler.py

Fixes an inadvertent change to the deterministic sampler 2nd order correction

Revert incorrect line in deterministic sampler

---

test/datapipes/common/cuda_graphs.py
test/utils/test_capture.py

The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Modernize logger interface

---

physicsnemo/utils/generative/__init__.py

In a previous PR `physicsnemo.utils.generative` has been renamed into `physicsnemo.utils.diffusion`. This PR adds a patch that:
- Defines aliases, such that all objects that used to exist in `physicsnemo.utils.generative` are still accessible and point to their counterparts in `physicsnemo.utils.diffusion`
- Prints a warning message when importing from `physicsnemo.utils.generative`, to inform the user about this deprecation process.

Patch for deprecation of generative utils

---

physicsnemo/utils/profiling/line_profile.py

Reduce profiling output by not printing profiles for functions that don't get called.

[Minor] Profiling Cleanup

---

CHANGELOG.md
physicsnemo/datapipes/healpix/data_modules.py

Fixes #988, using the test dataset object to instantiate `DistributedSampler`. As far as I can tell none of the examples or current known use-cases are exposed to this issue due to not using the `test_dataloader` method in distributed mode, but good to fix in general.

Fix healpix test dataloader DistributedSampler

---

examples/cfd/external_aerodynamics/domino/requirements.txt
examples/cfd/external_aerodynamics/domino/src/inference_on_stl.py
examples/cfd/external_aerodynamics/domino/src/train.py
physicsnemo/datapipes/cae/domino_datapipe.py
physicsnemo/utils/domino/utils.py
test/utils/test_domino_utils.py

Major changes:
- Adds complete function docstrings with argument definitions, return type definitions, notes on what exceptions can raise, type hints, and example usages.
- Refactors to use `pathlib.Path` over `os.path` for file path management (preferred since Python 3.4) [[1](https://www.reddit.com/r/learnpython/comments/i29h6j/when_or_why_should_i_use_pathlibpath_over_ospath/), [2](https://medium.com/@barila/choose-your-path-pythons-pathlib-vs-os-path-4de0b1e752dd)]
- Fixes functions that have mutable default values (e.g., defaulting an argument to a list, rather than a tuple) - [this should essentially-never be used](https://www.geeksforgeeks.org/python/use-mutable-default-value-as-an-argument-in-python/), and leads to very-difficult-to-trace bugs.
- Removes a usage of `from {package} …

Refactor on DoMINO `utils.py` to improve code quality

---

CHANGELOG.md
physicsnemo/models/dlwp_healpix_layers/healpix_layers.py

Adjusts `HEALPixLayer` to use the earth2grid padding kernels, if they are available, rather than a proprietary path that is not generally available. Will raise a warning if earth2grid is not found.

Use earth2grid HEALPixPad kernels when possible

---

physicsnemo/models/unet/unet.py

Fixes: https://github.com/NVIDIA/physicsnemo/issues/899

Refactor ReshapedLayerNorm to handle missing transformer_engine import gracefully

---

Dockerfile
physicsnemo/__init__.py
pyproject.toml

Setuptools SCM has introduced some major changes that are breaking the builds. This temporarily upper bounds the setuptools-scm version which makes the builds pass. Once the stable release is available, we can remove this upper bound. 
As of Aug 11, lot of releases of setuptools-scm are being yanked: https://setuptools-scm.readthedocs.io/en/latest/changelog/

Hot fixes for release

---

CHANGELOG.md
physicsnemo/datapipes/cae/domino_datapipe.py
test/datapipes/test_domino_datapipe.py

This PR is mostly adding further test coverage of Domino's datapipe, to enhance out ability to catch errors.
Only single-gpu tests here.

Add significantly more coverage of the domino datapipe to catch more errors

---

physicsnemo/distributed/shard_utils/__init__.py
physicsnemo/distributed/shard_utils/knn.py
test/distributed/shard_tensor/ops/test_knn.py
test/distributed/shard_tensor/ops/utils.py

This PR adds a distributed wrapper for the cuml based kNN tool in physicsnemo.  It only applies to CUDA tensors, but ShardTensor is CUDA-centric anyways.
Eventually, this is needed for the refactor of the domino pipeline and domain parallelism, but I've split it off here to be standalone and more easily reviewed.

Add a distributed implementation of kNN + testing.
